name: Upsert Infrastructure

on:
  workflow_dispatch: # Manual trigger
  schedule:
  - cron: '0 1 * * 1' # 1AM (UTC) every monday -- this run will clean up potential old policies
  push:
    branches: [prod, dev]

env:
  WORKSPACE: ${{ github.ref_name }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  TF_VAR_region: eu-north-1
  TF_VAR_organization: carlssonk
  TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  TF_VAR_cleanup_policies: ${{ github.event_name == 'schedule' }}

jobs:
  check_deploy_condition:
    name: Should Deploy Condition
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check.outputs.should_deploy }}
    steps:
      - id: check
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ !contains(github.event.head_commit.message, '[DESTROY]') }}" == "true" ]]; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "should_deploy=false" >> $GITHUB_OUTPUT
          fi

  deploy:
    name: Deploy
    needs: check_deploy_condition
    if: needs.check_deploy_condition.outputs.should_deploy == 'true'
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/terraform-execution-role
          aws-region: ${{ env.TF_VAR_region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Run Terraform for IAM and Resources
        run: |
          for step in iam resources; do
            echo "Running Terraform for $step"
            
            terraform init -reconfigure \
              -backend-config="encrypt=true" \
              -backend-config="region=${{ env.TF_VAR_region }}" \
              -backend-config="bucket=${{ env.TF_VAR_organization }}-terraform-state-bucket-${{ env.WORKSPACE }}" \
              -backend-config="dynamodb_table=${{ env.TF_VAR_organization }}-terraform-lock-table-${{ env.WORKSPACE }}" \
              -backend-config="key=${step}/terraform.tfstate"
            
            terraform workspace select ${{ env.WORKSPACE }} || terraform workspace new ${{ env.WORKSPACE }}
            
            python create_globals.py '${{ toJson(env) }}' workflow_step=$step
            
            chmod +x retry_command.sh
            if ! ./retry_command.sh "terraform apply -auto-approve"; then
              echo "Terraform apply failed after all retry attempts"
              exit 1
            fi
          done