name: Upsert Infrastructure

on:
  workflow_dispatch: # Manual trigger
  schedule:
  - cron: '0 1 * * 1' # 1AM (UTC) every monday -- this run will clean up unused policies
  push:
    branches: [prod, dev]
  pull_request:
    branches: [prod, dev]
  
concurrency: 
  group: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
  cancel-in-progress: false

env:
  TARGET_BRANCH: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
  TF_VAR_AWS_REGION: ${{ vars.AWS_REGION }}
  TF_VAR_ORGANIZATION: ${{ vars.ORGANIZATION }}
  TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  TF_VAR_cleanup_policies: ${{ github.event_name == 'schedule' }}

jobs:
  check_run:
    name: Should run condition
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - id: check
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ !contains(github.event.head_commit.message, '[DESTROY]') }}" == "true" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" || "${{ github.event_name }}" == "pull_request" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  terraform_operation:
    name: Terraform Operation
    needs: check_run
    if: needs.check_run.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    strategy:
      matrix:
        step: [iam, resources]
      fail-fast: true
      max-parallel: 1
    steps:
      - name: Set TF_VAR_workflow_step
        run: echo "TF_VAR_workflow_step=${{ matrix.step }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/terraform-execution-role
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Symlink modules
        run: |
          chmod +x symlink_modules.sh
          ./symlink_modules.sh ${{ matrix.step }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="encrypt=true" \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="bucket=${{ vars.ORGANIZATION }}-terraform-state-bucket-${{ env.TARGET_BRANCH }}" \
            -backend-config="dynamodb_table=${{ vars.ORGANIZATION }}-terraform-lock-table-${{ env.TARGET_BRANCH }}" \
            -backend-config="key=${{ matrix.step }}/terraform.tfstate"

      - name: Prepare Environment
        run: |
          python create_globals.py '${{ toJson(vars) }}' workflow_step=${{ env.TF_VAR_workflow_step }} cleanup_policies=${{ env.TF_VAR_cleanup_policies }}
          terraform workspace select ${{ env.TARGET_BRANCH }} || terraform workspace new ${{ env.TARGET_BRANCH }}
          chmod +x retry_command.sh
          chmod +x symlink_modules.sh
          ./symlink_modules.sh ${{ matrix.step }}

      - name: Check for State Removal Command
        if: matrix.step == 'resources'
        id: check_commit
        run: |
          commit_message=$(git log -1 --pretty=%B)
          if echo "$commit_message" | grep -q "^tf-rm:"; then
            echo "remove_resource=true" >> $GITHUB_OUTPUT
            echo "resource_address=$(echo "$commit_message" | sed -n 's/^tf-rm: *//p')" >> $GITHUB_OUTPUT
          else
            echo "remove_resource=false" >> $GITHUB_OUTPUT
          fi

      - name: Remove Resource from Terraform State
        if: matrix.step == 'resources' && steps.check_commit.outputs.remove_resource == 'true'
        run: |
          terraform state rm '${{ steps.check_commit.outputs.resource_address }}'
        continue-on-error: true

      - name: ${{ (github.event_name == 'pull_request' && 'Terraform Plan') || 'Terraform Apply' }}
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            terraform plan ${{ matrix.step == 'iam' && '-lock=false' || '' }}
          else
            if ! ./retry_command.sh "terraform apply ${{ matrix.step == 'iam' && '-lock=false' || '' }} -auto-approve"; then
              echo "Terraform failed after all retry attempts"
              exit 1
            fi
          fi

      - name: Terraform Show
        if: matrix.step == 'resources'
        run: terraform show -json | sed -n '2p' > terraform_show.json

      - name: Check for changes
        if: matrix.step == 'resources'
        id: git-check
        run: |
          git add terraform_show.json
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "[skip ci] Update terraform_show.json" -a

      - name: Push changes
        if: steps.git-check.outputs.changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}