name: Upsert Infrastructure

on:
  push:
    branches: [prod, dev]

environment: ${{ github.ref_name }}
env:
  TF_VAR_region: eu-north-1
  TF_VAR_organization: carlssonk
  TF_VAR_environment: ${{ github.ref_name }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TF_VAR_region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Apply
        run: |
          terraform init -backend-config=backend-config.hcl -backend-config="org=${{ env.TF_VAR_organization }}" -backend-config="env=${{ env.TF_VAR_environment }}"
          terraform apply -auto-approve